basePath: '{{.BasePath}}'
definitions:
  model.ApiError:
    properties:
      details:
        type: string
      message:
        type: string
      status:
        type: integer
      ts:
        type: string
    type: object
  model.OpResult:
    properties:
      operation:
        type: object
      result:
        type: object
      success:
        type: boolean
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /v1/div:
    get:
      description: Should return status 200 with an division operation result
      operationId: v1GetDiv
      parameters:
        - description: division operation numerator
          in: query
          name: x
          required: true
          type: integer
        - description: division operation denominator
          in: query
          name: "y"
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OpResult'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ApiError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/model.ApiError'
            type: object
      summary: Division using request url params
    put:
      consumes:
        - application/json
      description: Should return status 200 with an division operation result
      operationId: v1PutDiv
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OpResult'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ApiError'
            type: object
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/model.ApiError'
            type: object
      summary: Division using request body
  /v2/div:
    get:
      description: Should return status 200 with an division operation result
      operationId: v2GetDiv
      parameters:
        - description: division operation numerator
          in: query
          name: x
          required: true
          type: integer
        - description: division operation denominator
          in: query
          name: "y"
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OpResult'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ApiError'
            type: object
      summary: Division using request url params
    put:
      consumes:
        - application/json
      description: Should return status 200 with an division operation result
      operationId: v2PutDiv
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.OpResult'
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ApiError'
            type: object
      summary: Division using request body
swagger: "2.0"
